## 该注册服务器的端口
server:
  port: 8001

spring:
  application:
    ## 应用启动名称
    name: eureka-server
## eureka配置
eureka:
  instance:
    ## 注册服务器的名称
    hostname: localhost
  client:
    ## 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    ## 是否从eureka服务器获取注册信息，所以这里是false
    fetch-registry: false
    ## 是否注册自身到eureka服务器,因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    register-with-eureka: false
    serviceUrl:
      ## 服务发布的地址
      defaultZone: http://localhost:8001/eureka/